### PR TITLE
Rework `lrauv_ignition_plugins` package

### PR DESCRIPTION
**Pull request by hidmic**
This PR reworks the `lrauv_ignition_plugins` package in preparation for the `lrauv_system_tests` package. Namely, it:

- Exports CMake targets for downstream usage
- Adds colcon hook equivalent for sh-like shells
- Removes all tests (migrated to `lrauv_system_tests`)

### CODE REVIEW

**Review by arjo129 — CHANGES_REQUESTED** [review]
Ideally this PR should have tests passing since there are no unit tests. I think you are missing the python bindings dependency. See #200.

**Review by arjo129 — APPROVED** [review]

**Comment by hidmic** [comment]
Thank you for the review and the quick fix @arjo129 !

**Comment by braanan** [comment]
@hidmic Looks like this PR will need one more adjustment to catch up with the recent ign version updates (cmake2 -> cmake3) — should I push this fix here or in some other PR?

**Comment by braanan** [comment]
Went for it.

**Review by braanan — APPROVED** [review]

**Pull request merged**
