### PR TITLE
Update Garden dependencies

### PR DESCRIPTION
**Pull request by chapulina**
Quick update since we have new dependencies on Garden. Note that `ign-math`, `sdf` and `ign-physics` have also been bumped, so be sure to update your local workspaces.

### CODE REVIEW

**Comment by chapulina** [comment]
All tests crashed on shutdown with "Child aborted". I can't reproduce it locally :thinking:

**Comment by arjo129** [comment]
Hmmm I'm able to reproduce the problems locally. I recommend running locally with `--no-cache` option so that the latest ignition garden binaries are fetched and you are certain that docker is loading the latest version of the garden binaries. It seems like we managed to introduce a double free somewhere upstream in ignition.

**Comment by chapulina** [comment]
Ah got it, let me try the nightlies, I was trying from source

**Comment by tfoote** [comment]
The CI failed with an odd failure: 

```
9: [Msg] Completed command [/home/developer/lrauv_ws/src/lrauv/lrauv_ignition_plugins/../../lrauv-application/bin/LRAUV -x 'run /home/developer/lrauv_ws/src/lrauv/lrauv_ignition_plugins/../../lrauv-application/Missions/RegressionTests/IgnitionTests/testPitchMass.xml quitAtEnd' 2>&1]
9: [Msg] Logged [28577] poses
9: [       OK ] LrauvTestFixture.PitchMass (17149 ms)
9: [----------] 1 test from LrauvTestFixture (17149 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 1 test from 1 test suite ran. (17149 ms total)
9: [  PASSED  ] 1 test.
9: double free or corruption (!prev)
 9/16 Test  #9: LrauvTestFixture.PitchMass ..................Child aborted***Exception:  17.48 sec
```

**Comment by chapulina** [comment]
I got a backtrace

```
Thread 1 "test_controller" received signal SIGABRT, Aborted.
0x00007ffff72e218b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff72e218b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff72c1859 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff732c3ee in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff733447c in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff733612c in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff7c4c83d in std::_Rb_tree<ignition::common::MaterialDensity::Type, std::pair<ignition::common::MaterialDensity::Type const, double>, std::_Select1st<std::pair<ignition::common::MaterialDensity::Type const, double> >, std::less<ignition::common::MaterialDensity::Type>, std::allocator<std::pair<ignition::common::MaterialDensity::Type const, double> > >::_M_erase(std::_Rb_tree_node<std::pair<ignition::common::MaterialDensity::Type const, double> >*) () from /usr/lib/x86_64-linux-gnu/libignition-common4.so.4
#6  0x00007ffff72e615e in __cxa_finalize () from /usr/lib/x86_64-linux-gnu/libc.so.6
#7  0x00007ffff7c2d547 in ?? () from /usr/lib/x86_64-linux-gnu/libignition-common4.so.4
#8  0x00007fffffffdf70 in ?? ()
```

The important detail there is `common4` instead of `common5`. It looks like some debs are still linked against the old version. I'm investigating.

**Comment by chapulina** [comment]
The `ign-launch6` nightlies are broken and still depend on `ign-common4`:

```
$ apt-cache rdepends --installed libignition-common4-dev
libignition-common4-dev
Reverse Depends:
  libignition-launch6-dev
```

https://build.osrfoundation.org/job/ign-launch6-debbuilder/

**Comment by chapulina** [comment]
Alright, all we needed was an upgrade.

It looks like we don't need to publish an updated MBARI image either. Although the controller is currently linking to `ign-math6`, that doesn't affect the transport interface, so it can still communicate correctly with the simulation.

**Review by tfoote — CHANGES_REQUESTED** [review]
This approach is a bit fragile with caching on the Dockerfile. The upgrade will fail if the update hasn't been run recently. (ala cached) We should fold it into the chain of commands above installing ignition-garden instead of having it on it's own line.

**Comment by tfoote** [comment]
Proposed fix #130

**Comment by chapulina** [comment]
Thanks for the fix, @tfoote , merged it in

**Review by tfoote — APPROVED** [review]
lgtm

**Comment by chapulina** [comment]
Ouch, that didn't work though

**Comment by chapulina** [comment]
@tfoote , any suggestion on the correct way of making sure these are upgraded as well?

```
2022-01-05T19:40:56.9588414Z The following packages have been kept back:
2022-01-05T19:40:56.9590212Z   ignition-garden libignition-fuel-tools8 libignition-fuel-tools8-dev
2022-01-05T19:40:56.9591776Z   libignition-gazebo7 libignition-gazebo7-dev libignition-gazebo7-plugins
2022-01-05T19:40:56.9596759Z   libignition-gui7 libignition-gui7-dev libignition-launch6
2022-01-05T19:40:56.9598481Z   libignition-launch6-dev libignition-msgs9 libignition-msgs9-dev
2022-01-05T19:40:56.9618605Z   libignition-rendering7 libignition-rendering7-core-dev
2022-01-05T19:40:56.9621863Z   libignition-rendering7-dev libignition-rendering7-ogre1
2022-01-05T19:40:56.9624794Z   libignition-rendering7-ogre1-dev libignition-rendering7-ogre2
2022-01-05T19:40:56.9627625Z   libignition-rendering7-ogre2-dev libignition-sensors7
2022-01-05T19:40:56.9631307Z   libignition-sensors7-air-pressure libignition-sensors7-air-pressure-dev
2022-01-05T19:40:56.9634815Z   libignition-sensors7-altimeter libignition-sensors7-altimeter-dev
2022-01-05T19:40:56.9637601Z   libignition-sensors7-camera libignition-sensors7-camera-dev
2022-01-05T19:40:56.9639863Z   libignition-sensors7-core-dev libignition-sensors7-depth-camera
2022-01-05T19:40:56.9641710Z   libignition-sensors7-depth-camera-dev libignition-sensors7-dev
2022-01-05T19:40:56.9643638Z   libignition-sensors7-force-torque libignition-sensors7-force-torque-dev
2022-01-05T19:40:56.9645968Z   libignition-sensors7-gpu-lidar libignition-sensors7-gpu-lidar-dev
2022-01-05T19:40:56.9647596Z   libignition-sensors7-imu libignition-sensors7-imu-dev
2022-01-05T19:40:56.9649099Z   libignition-sensors7-lidar libignition-sensors7-lidar-dev
2022-01-05T19:40:56.9650985Z   libignition-sensors7-logical-camera libignition-sensors7-logical-camera-dev
2022-01-05T19:40:56.9653138Z   libignition-sensors7-magnetometer libignition-sensors7-magnetometer-dev
2022-01-05T19:40:56.9655093Z   libignition-sensors7-rendering libignition-sensors7-rendering-dev
2022-01-05T19:40:56.9657022Z   libignition-sensors7-rgbd-camera libignition-sensors7-rgbd-camera-dev
2022-01-05T19:40:56.9658734Z   libignition-sensors7-segmentation-camera
2022-01-05T19:40:56.9660726Z   libignition-sensors7-segmentation-camera-dev
2022-01-05T19:40:56.9662766Z   libignition-sensors7-thermal-camera libignition-sensors7-thermal-camera-dev
2022-01-05T19:40:56.9664987Z   libignition-sensors7-wide-angle-camera
2022-01-05T19:40:56.9666682Z   libignition-sensors7-wide-angle-camera-dev libignition-transport12
2022-01-05T19:40:56.9668906Z   libignition-transport12-core-dev libignition-transport12-dev
2022-01-05T19:40:56.9670901Z   libignition-transport12-log libignition-transport12-log-dev
```

**Comment by chapulina** [comment]
Kept the upgrade in the same `RUN` command, but after the install in e1ebc3a. Merging!

**Pull request merged**
