### PR TITLE
Fix added mass contribution.

### PR DESCRIPTION
**Pull request by arjo129**
I noticed that added mass was acting in the wrong direction. This was after visuallizing the individual forces separately (in this case added mass and damping forces). To be honest it still doesn't fix any of our outstanding issues.

Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
This PR is causing test failures. I'm not sure yet if we should update the tests or if there's something wrong with the PR. One thing I noticed in the tests is that this PR is exacerbating this issue: https://github.com/osrf/lrauv/issues/47

Is there a way we can unit test the plugin so we check what the high-level expectations are? i.e. move 2 vehicles forward, one with added mass enabled and one disabled, and check that the one affected by added mass is slower.

**Comment by arjo129** [comment]
I need to update test expectations. We can extract out the individual components a functions and unit test the functions as is. One of the problems I face is that I can't test the wrenches with the physics engine running (this would be ideal). Otherwise the easiest test is that the direction of the force should always oppose the direction of motion. For some remedy to 47 I would recommend looking at #57.

**Comment by chapulina** [comment]
> I can't test the wrenches with the physics engine running

Can you elaborate? I think it should be possible to test the hydrodynamics isolated in a world without gravity, buoyancy or lift-drag. Apply a force to the vehicle, and see if its resulting velocity is damped as expected?

> the direction of the force should always oppose the direction of motion

+1, I think this should help us detect sign errors

**Comment by tfoote** [comment]
> the direction of the force should always oppose the direction of motion

That's not exactly correct. Only when accelerating. When decelerating it will go in the direction of motion. It should be in the opposite of the direction of the acceleration.

**Comment by arjo129** [comment]
That's correct for the direction of the added mass, but the damping matrix would dominate at higher velocities.

**Comment by chapulina** [comment]
@arjo129 , how would you like to proceed here? Let me know if you need help updating the test expectations.

**Review by chapulina — APPROVED** [review]

**Pull request merged**
