### PR TITLE
Add above surface winds

### LINKED ISSUE #149: Surface winds
Add Ignition world plugin for simulation of surface winds (collaboration with Hamilton’s DOE).

### PR DESCRIPTION
**Pull request by hidmic**
Closes #149. This patch requires https://github.com/ignitionrobotics/ign-gazebo/pull/1357.

### CODE REVIEW

**Comment by hidmic** [comment]
Most tests will still fail because of #189, but surface winds' ones will pass.

**Comment by hidmic** [comment]
@arjo129 @braanan whenever you got the time, I could use a review :)

**Comment by arjo129** [comment]
Should we wait for the rework of the tests before merging this. I suspect we will need to move the tests into your new test package?

**Comment by hidmic** [comment]
> Should we wait for the rework of the tests before merging this. I suspect we will need to move the tests into your new test package?

Yes. Now that the merge train has started, it'll have to wait.

**Comment by hidmic** [comment]
Rebased to pull #204 in.

**Review by arjo129 — APPROVED** [review]
Tested and looks good to me.

**Pull request merged**
