### PR TITLE
Relocate DVL to payload section

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Follow-up after #213.

### CODE REVIEW

**Review by arjo129 — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
@arjo129 PTAL, there were a few _details_ lurking below the surface.

**Comment by hidmic** [comment]
Alright, our frame conventions are a bit of a mess.I'm going for minimal changes. We can rework them in the future.

**Comment by hidmic** [comment]
Yay, finally. Going in, in the interest of time.

**Pull request merged**
