### PR TITLE
Increase depth tolerance for spawn test

### PR DESCRIPTION
**Pull request by chapulina**
The test started failing, it looks like we're sinking more than usual.

### CODE REVIEW

**Review by arjo129 — APPROVED** [review]
Yeah I don't understand why though. We may need to investigate. I know in #89 that the vehicle is not sinking at all otherwise some other unit test would fail, but the spawned vehicle seems to sink... There may be yet another bug in the buoyancy plugin.

**Comment by chapulina** [comment]
> Yeah I don't understand why though. We may need to investigate. 

Yeah I'm not sure either. I think the only thing that changed and could affect this is the upstream buoyancy fix, which is already released.

I'll merge this, but we still need to fix the expectations for `PitchMass`. If not with #112 , then some other way.

**Comment by arjo129** [comment]
So I'm hoping that I can get #96 will go green by end of the day with the necessary fixes. That should allow pitchmass to work.

**Comment by chapulina** [comment]
> I'm hoping that I can get #96 will go green by end of the day with the necessary fixes. That should allow pitchmass to work.

My concern is that #96 is pretty large and it builds on top of another PR. So it should take a while to get it in. I think it's worth it getting CI green before we do all those large changes.

**Pull request merged**
