### PR TITLE
Minor fixes to empty_world/Dockerfile

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. A very minor issue with newline escaping in our Dockerfile.

### CODE REVIEW

**Comment by hidmic** [comment]
Hmm integration tests are failing hard on `master`.

**Comment by arjo129** [comment]
Something must have broken upstream *all* our tests are segfaulting.

**Review by arjo129 — APPROVED** [review]
This does not effect our core work flow or CI and seems to work for me.

**Review by tfoote — DISMISSED** [review]
This looks correct. The change likely has to do with triggering a rebuild and possibly a partial debian package update. 

We should probably be doing a dist-upgrade when we install from the osrfoundation.org repos. https://github.com/osrf/lrauv/pull/141 I think that upstream should be pinning dependencies or declaring conflicts to force a full upgrade when you enable the osrfoundation repos to avoid incompatibility.

**Review by tfoote — COMMENTED** [review]
The dist-upgrades look appropriate. If this is still failing I think that we have a bigger problem than the potential conflicting binary packages.

**Comment by arjo129** [comment]
I think the changes have been applied. Lets merge this as I realize the first instruction in our README is broken.

**Review by arjo129 — APPROVED** [review]

**Pull request merged**
