### PR TITLE
pull in main to facilitate gz namespcae updates

### PR DESCRIPTION
**Pull request by braanan**
Hi @adityapande-1995, 

Targeting your PR to pull in main with recent namespace changes and resolve conflicts. I also took the liberty and updating batt specific files with the gz namespace in place of the deprecated ignition namespace. Should be ready to merge with main with these updates.

Thanks, 
Ben

### CODE REVIEW

**Review by adityapande-1995 — APPROVED** [review]
Thanks Ben !

**Comment by adityapande-1995** [comment]
The YoYo, PitchMass, DepthVBS, and PitchDepthVBS tests are failing, but I'm not sure how they can be related to this PR.

**Comment by braanan** [comment]
Hmm... interesting. I'll try to reproduce on my local

**Comment by adityapande-1995** [comment]
I was able to reproduce the YoYo test error locally with this repo on ``main``

**Comment by braanan** [comment]
`test_yoyo_circle_mission` passes with my local build, so perhaps an issue with the Docker image I created? I'll look into that next.

**Comment by adityapande-1995** [comment]
It is also failing on the DVL PR now : https://github.com/osrf/lrauv/pull/212 cc @hidmic

**Comment by adityapande-1995** [comment]
The CI is failing due to LRAUV State msg ABI difference on the lrauv app side. I'l go ahead and merge this one into the battery msg branch.

**Pull request merged**
